//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drummond
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamento
    {
        public departamento()
        {
            this.DepartamentoSede = new HashSet<DepartamentoSede>();
            this.DepartamentoArea = new HashSet<DepartamentoArea>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<DepartamentoSede> DepartamentoSede { get; set; }
        public virtual ICollection<DepartamentoArea> DepartamentoArea { get; set; }
    }
}
