//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drummond
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloContainer : DbContext
    {
        public ModeloContainer()
            : base("name=ModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Cargos> CargosSet { get; set; }
        public virtual DbSet<Empleados> EmpleadosSet { get; set; }
        public virtual DbSet<departamento> departamentoSet { get; set; }
        public virtual DbSet<Sede> SedeSet { get; set; }
        public virtual DbSet<Subarea> SubareaSet { get; set; }
        public virtual DbSet<Grupo> GrupoSet { get; set; }
        public virtual DbSet<DepartamentoArea> DepartamentoAreaSet { get; set; }
        public virtual DbSet<DepartamentoSede> DepartamentoSedeSet { get; set; }
        public virtual DbSet<AreaSubarea> AreaSubareas { get; set; }
        public virtual DbSet<GrupoArea> GrupoAreas { get; set; }
    }
}
